import { expect, test, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { runLocalMaintenanceSql } from "./local-maintenance";
test.use({ trace: "off", screenshot: "off" });
test.beforeEach(() => {
  test.skip(!process.env.NEXT_PUBLIC_SUPABASE_URL?.startsWith("http://127.0.0.1:54321"), "Solo fixture ficticio local");
});
async function signIn(page: Page, email = "admin1@example.invalid") {
  await page.goto("/login");
  await page.getByLabel("Correo electrónico").fill(email);
  await page.getByLabel("Contraseña", { exact: true }).fill("Fictitious-Local-Only-2026!");
  await page.getByRole("button", { name: "Iniciar sesión" }).click();
  await expect(page).toHaveURL(/\/account$/);
}
async function fillProfile(page: Page, name: string, dni: string) {
  await page.goto("/admin/candidates/assisted");
  await expect(page.getByRole("heading", { name: "Atención presencial" })).toBeVisible();
  await page.getByLabel("Nombre y apellido").fill(name);
  await page.getByLabel("DNI", { exact: true }).fill(dni);
  await page.getByLabel("Teléfono", { exact: true }).fill("3410000000");
}
test("atención sin PDF, derivación protegida, consentimiento y vinculación presencial con historial", async ({ page, browser, request }) => {
  test.setTimeout(120_000);
  const suffix = Date.now().toString().slice(-5);
  const name = `Persona asistida E2E ${suffix}`;
  const dni = `98${suffix}1`;
  await signIn(page);
  await fillProfile(page, name, dni);
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.getByRole("button", { name: "Comprobar duplicados y guardar" }).click();
  await expect(page).toHaveURL(/\/assisted\/[0-9a-f-]{36}$/);
  const id = page.url().split("/").pop()!;
  expect(id).toMatch(/^[0-9a-f-]{36}$/);
  const maintenance = `/admin/candidates/assisted/${id}`;
  const detail = `/admin/candidates/${id}`;
  await page.getByLabel("Localidad laboral").fill("Funes");
  await page.getByLabel("Habilidades y experiencia").fill("Experiencia ficticia en atención municipal");
  await page.getByLabel("Categoría ficticia A", { exact: true }).check();
  await page.getByLabel("Interés: Categoría ficticia B").check();
  await page.getByRole("button", { name: "Guardar perfil asistido" }).click();
  await expect(page.getByText("Perfil guardado.", { exact: true })).toBeVisible();
  await page.reload();
  await page.getByLabel("Confirmo la decisión de la persona atendida.").check();
  await page.getByRole("button", { name: "Guardar consentimiento asistido" }).click();
  await expect(page.getByText("Consentimiento registrado.")).toBeVisible();
  await page.reload();
  await page.getByRole("button", { name: "Activar para evaluación interna" }).click();
  await expect(page.getByText("Estado: Activo.", { exact: false })).toBeVisible();
  await page.reload();
  await page.getByLabel("Tipo", { exact: true }).selectOption("record_training_guidance");
  await page.getByLabel("Contenido interno").fill("Orientación ficticia de entrevista presencial");
  await page.getByRole("button", { name: "Guardar nota" }).click();
  await expect.poll(() => runLocalMaintenanceSql(`select count(*) from public.internal_notes where candidate_id='${id}'`)).toBe("1");
  await page.goto(detail);
  await expect(page.getByText("Orientación ficticia de entrevista presencial")).toBeVisible();
  const hash = createHash("md5").update("funes-demo-v1:opening:1").digest("hex");
  const opening = `${hash.slice(0,8)}-${hash.slice(8,12)}-${hash.slice(12,16)}-${hash.slice(16,20)}-${hash.slice(20)}`;
  await page.getByLabel("Oferta", { exact: true }).selectOption(opening);
  await page.getByRole("button", { name: "Crear nominación" }).click();
  await expect(page).toHaveURL(/\/admin\/participations\/[0-9a-f-]{36}$/);
  const participation = page.url();
  await page.getByLabel("Acción", { exact: true }).selectOption("skip_to_preselected");
  await page.getByRole("textbox", { name: "Motivo interno" }).fill("Evaluación presencial ficticia realizada");
  await page.getByRole("button", { name: "Registrar acción" }).click();
  const status = page.getByRole("status").filter({ hasText: "Resultado o estado vigente" });
  await expect(status).toContainText("Preseleccionada");
  await page.getByLabel("Acción", { exact: true }).selectOption("refer");
  await page.getByRole("button", { name: "Registrar acción" }).click();
  await expect(page.getByRole("alert").filter({ hasText: "Cargá un CV PDF válido" })).toBeVisible();
  await expect(status).toContainText("Preseleccionada");
  await page.goto(detail);
  await page.getByLabel("Archivo PDF").setInputFiles(join(process.cwd(), "tests/fixtures/cv-fictitious.pdf"));
  await page.getByRole("button", { name: "Cargar CV", exact: true }).click();
  await expect(page.getByText("CV guardado.")).toBeVisible();
  await page.goto(participation);
  await page.getByLabel("Acción", { exact: true }).selectOption("refer");
  await page.getByRole("button", { name: "Registrar acción" }).click();
  await expect(status).toContainText("Derivada");

  const candidateContext = await browser.newContext({ baseURL: "http://127.0.0.1:3000" });
  const companyContext = await browser.newContext({ baseURL: "http://127.0.0.1:3000" });
  try {
    const company = await companyContext.newPage();
    await signIn(company, "company1@example.invalid");
    await company.goto(`/company/openings/${opening}/referrals`);
    await expect(company.getByText(name, { exact: true })).toBeVisible();
    await expect(company.locator("body")).not.toContainText("Orientación ficticia de entrevista presencial");
    const candidate = await candidateContext.newPage();
    const email = `assisted-e2e-${suffix}@example.invalid`;
    await candidate.goto("/registro/candidato");
    await candidate.getByLabel("Nombre y apellido").fill(name);
    await candidate.getByLabel("DNI").fill(dni);
    await candidate.getByLabel("Correo electrónico").fill(email);
    await candidate.getByLabel("Contraseña").fill("Fictitious-Local-Only-2026!");
    await candidate.getByRole("button", { name: "Crear cuenta candidata" }).click();
    await expect(candidate.getByRole("status")).toContainText("recibirás un enlace");
    let mailId = "";
    await expect.poll(async () => {
      const inbox = await (await request.get("http://127.0.0.1:54324/api/v1/messages")).json() as { messages: { ID: string; To: { Address: string }[] }[] };
      mailId = inbox.messages.find((m) => m.To.some((r) => r.Address === email))?.ID ?? "";
      return Boolean(mailId);
    }).toBe(true);
    const mail = await (await request.get(`http://127.0.0.1:54324/api/v1/message/${mailId}`)).json() as { Text?: string; HTML?: string };
    const link = (mail.Text ?? mail.HTML ?? "").match(/https?:\/\/[^\s"<>]+/)?.[0]?.replaceAll("&amp;", "&");
    expect(link).toBeTruthy();
    await candidate.goto(link!);
    await candidate.goto("/candidato/perfil");
    await expect(candidate.locator("body")).toContainText(/presencial/);
    const before = runLocalMaintenanceSql(`select jsonb_build_object('origin',origin,'status',status,'consents',(select count(*) from public.candidate_consents where candidate_id='${id}'),'cases',(select count(*) from public.participations where candidate_id='${id}'),'notes',(select count(*) from public.internal_notes where candidate_id='${id}')) from public.candidate_profiles where id='${id}'`);
    await page.goto(maintenance);
    await page.getByLabel("Cuenta solicitante").selectOption({ label: `${email} · verificado` });
    await page.getByLabel("DNI exhibido", { exact: true }).fill("98000009");
    await page.getByLabel("Motivo de vinculación").fill("Identidad comprobada en atención ficticia");
    await page.getByLabel(/Comprobé presencialmente/).check();
    await page.getByRole("button", { name: "Vincular conservando historial" }).click();
    await expect(page.getByText(/Vinculación bloqueada por conflicto/)).toBeVisible();
    await page.getByLabel("DNI exhibido", { exact: true }).fill(dni);
    await page.getByRole("button", { name: "Vincular conservando historial" }).click();
    await expect(page.getByText(/Estado: Activo.*Cuenta vinculada/)).toBeVisible();
    const after = runLocalMaintenanceSql(`select jsonb_build_object('origin',origin,'status',status,'consents',(select count(*) from public.candidate_consents where candidate_id='${id}'),'cases',(select count(*) from public.participations where candidate_id='${id}'),'notes',(select count(*) from public.internal_notes where candidate_id='${id}')) from public.candidate_profiles where id='${id}'`);
    expect(after).toBe(before);
    await candidate.reload();
    await expect(candidate.getByRole("heading", { name: "Mi perfil" })).toBeVisible();
    await expect(candidate.getByLabel("Habilidades y experiencia")).toHaveValue("Experiencia ficticia en atención municipal");
    await expect(candidate.locator("body")).not.toContainText("Orientación ficticia de entrevista presencial");
    expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  } finally { await candidateContext.close(); await companyContext.close(); }
});

test("duplicados exige las tres decisiones, campos confirmados y corrección antes de crear separado", async ({ page }) => {
  const suffix = Date.now().toString().slice(-5);
  const dni = `97${suffix}1`;
  const name = `Duplicado ficticio ${suffix}`;
  await signIn(page);
  await fillProfile(page, name, dni);
  await page.getByRole("button", { name: "Comprobar duplicados y guardar" }).click();
  await expect(page).toHaveURL(/\/assisted\/[0-9a-f-]{36}$/);
  const original = page.url();
  await fillProfile(page, "Nombre que no debe sobrescribir", dni);
  await page.getByRole("button", { name: "Comprobar duplicados y guardar" }).click();
  await expect(page.getByText("Hay coincidencias por DNI o correo.", { exact: false })).toBeVisible();
  await page.getByLabel("Perfil coincidente").selectOption({ label: `${name} · DNI` });
  await page.getByRole("combobox", { name: "Decisión", exact: true }).selectOption("use_or_update_existing");
  await page.getByLabel("Motivo de la decisión").fill("Usar la misma persona ficticia sin cambiar datos");
  await page.getByRole("button", { name: "Confirmar decisión" }).click();
  await expect(page).toHaveURL(original);
  await expect(page.getByLabel("Nombre y apellido")).toHaveValue(name);
  await fillProfile(page, name, dni);
  await page.getByRole("button", { name: "Comprobar duplicados y guardar" }).click();
  await page.getByLabel("Perfil coincidente").selectOption({ label: `${name} · DNI` });
  await page.getByRole("combobox", { name: "Decisión", exact: true }).selectOption("correct_and_create");
  await page.getByLabel("Motivo de la decisión").fill("Error de identificación ficticio corregido");
  await page.getByLabel("DNI", { exact: true }).fill(`97${suffix}2`);
  await page.getByRole("button", { name: "Confirmar decisión" }).click();
  await expect(page).toHaveURL(/\/assisted\/[0-9a-f-]{36}$/);
  expect(page.url()).not.toBe(original);
  await fillProfile(page, name, dni);
  await page.getByRole("button", { name: "Comprobar duplicados y guardar" }).click();
  await page.getByLabel("Perfil coincidente").selectOption({ label: `${name} · DNI` });
  await page.getByRole("combobox", { name: "Decisión", exact: true }).selectOption("reject");
  await page.getByLabel("Motivo de la decisión").fill("Alta ficticia rechazada");
  await page.getByRole("button", { name: "Confirmar decisión" }).click();
  await expect(page.getByText("Alta rechazada con motivo registrado.")).toBeVisible();
});
